- hosts: localhost
  become_method: sudo
  gather_facts: true

  vars:
    is_64_bit: false
    image_folder: ./
    image_name: 2021-10-30-raspios-bullseye-armhf
    raspi_os_url: https://downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2021-11-08/2021-10-30-raspios-bullseye-armhf.zip
  tasks:

    - name: Check if we have it locally
      stat:
        path: "{{ image_folder }}/{{ image_name }}.zip"
      register: image_exists

    - set_fact:
        image_name: 2021-10-30-raspios-bullseye-arm64
        raspi_os_url: https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-11-08/2021-10-30-raspios-bullseye-arm64.zip
      when: is_64_bit | bool

    - name: Download image
      get_url:
        url: "{{ raspi_os_url }}"
        force: false
        dest: "{{ image_folder }}"
      when: image_exists.stat.exists == False or 
            stat_result.stat is not undefined and stat_result.stat.exists == False
