#- import_playbook: mount_pi_top_os.yml

- hosts: pi_top_os:192.168.*:!localhost
  gather_facts: true
  environment:
    # For some reason ansible only picks up the sbin's by default, which causes apt-key to fail
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-11-openjdk-armhf/bin"
  vars:
    repo_name: experimental
    distro_name: bullseye
    # TODO: these vars should be received from previous steps
    image_folder: ./
    # image_name: 2021-05-07-raspios-buster-armhf-full
    image_name: 2021-06-18-raspios-bullseye-armhf

  tasks:
    - name: Upgrade Raspberry Pi OS
      apt:
        state: latest
        update_cache: true
        install_recommends: true
      register: apt_status
      retries: 5
      until: apt_status is success

    - name: Install pi-topOS GPG key
      apt:
        name: pi-top-os-archive-keyring
        state: latest

    - name: Add pi-topOS apt repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/pi-top-os-archive-keyring.asc] https://pkg.pi-top.com/{{ repo_name }}/debian/ {{ distro_name }} main"
        filename: "pi-top-os"
        update_cache: true

    - name: Install pt-os
      apt:
        name: pt-os
        update_cache: true
        state: latest
        install_recommends: true
        default_release: "{{ distro_name }}"

      register: apt_status
      retries: 5
      until: apt_status is success

#########################
# Recovery installation #
#########################
    # TODO:
    #     move to separate playbook/script? create-empty-pi-top-image.sh?
    #     seems better to handle at the point where the partition is being created!
    - name: Get information about recovery releases
      uri:
        url: https://api.github.com/repos/pi-top/pi-topOS-Recovery/releases/latest
        return_content: true
      register: json_response

    - name: Download latest recovery
      get_url:
        url: "{{ json_response.json.assets[0].browser_download_url }}"
        dest: /tmp/recovery.zip

    - name: Unzip recovery into partition 1
      unarchive:
        remote_src: yes
        src: /tmp/recovery.zip
        dest: /recovery

    - name: Copy autoboot.txt
      copy:
        src: files/autoboot.txt
        dest: /recovery/autoboot.txt
        mode: '0755'

    # TODO: move to a new stage
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        update_cache: true
      register: apt_status
      retries: 5
      until: apt_status is success
