- hosts: localhost
  become_method: sudo
  gather_facts: true

  vars:
    image_folder: ./
    # TODO: use 'image_name' on localhost if already defined
    image_name: 2022-09-22-raspios-bullseye-armhf
    raspi_os_mount_point: /tmp/raspi-os
  tasks:

    - name: Don't continue if already mounted...
      stat:
        path: "{{ raspi_os_mount_point }}/boot"
      register: raspi_os_file_details

    - meta: end_host
      when: raspi_os_file_details.stat.exists

    - set_fact:
        image_path: "{{ image_folder }}/{{ image_name }}.img"

    - name: Extract OS image
      shell: "unxz -kv {{ image_folder }}/{{ image_name }}.img.xz"

    # Ensure that a loopback device is associated with image

    - name: List the loop device(s) associated with image
      command: "losetup --output=NAME --associated {{image_path}}"
      register: loop_device_check

    - name: Create a new loopback device
      command: "losetup -f"
      become: true
      when: loop_device_check.stdout_lines[1] is not defined

    - name: If none, mount all the partitions to a loop device
      command: "partx --add --verbose {{image_path}}"
      become: true
      when: loop_device_check.stdout_lines[1] is not defined

    # Mount loopback device to mountpoint

    - name: blkid raspi boot
      shell: "blkid -l -o export -t LABEL='boot'"
      register: blkid_raspi_boot_stdout

    - debug:
        var: blkid_raspi_boot_stdout
        verbosity: 2

    - name: blkid raspi rootfs
      shell: "blkid -l -o export -t LABEL='rootfs'"
      register: blkid_raspi_rootfs_stdout

    - debug:
        var: blkid_raspi_rootfs_stdout
        verbosity: 2

    - set_fact:
        boot:
          fstype: "{{ blkid_raspi_boot_stdout.stdout_lines[-2].replace('TYPE=', '') }}"
          partuuid: "{{ blkid_raspi_boot_stdout.stdout_lines[-1].replace('PARTUUID=', '') }}"
        rootfs:
          fstype: "{{ blkid_raspi_rootfs_stdout.stdout_lines[-2].replace('TYPE=', '') }}"
          partuuid: "{{ blkid_raspi_rootfs_stdout.stdout_lines[-1].replace('PARTUUID=', '') }}"

    - debug:
        var: boot
        verbosity: 2

    - debug:
        var: rootfs
        verbosity: 2

    - name: Create mount point
      file:
        path: "{{raspi_os_mount_point}}"
        state: directory
        recurse: true

    - name: Mount rootfs
      become: true
      mount:
        path: "{{ raspi_os_mount_point }}"
        src: "PARTUUID={{ rootfs.partuuid }}"
        fstype: "{{ rootfs.fstype }}"
        fstab: /tmp/raspi-os-fstab
        opts: defaults,noatime
        state: mounted

    - name: Mount boot
      become: true
      mount:
        path: "{{ raspi_os_mount_point }}/boot"
        src: "PARTUUID={{ boot.partuuid }}"
        fstype: "{{ boot.fstype }}"
        fstab: /tmp/raspi-os-fstab
        opts: defaults
        state: mounted

    # Enable chroot to ARM: https://wiki.debian.org/QemuUserEmulation
    - name: Copy qemu-arm-static to Raspberry Pi OS to enable chrooting
      become: true
      copy:
        src: /usr/bin/qemu-arm-static
        dest: "{{ raspi_os_mount_point }}/usr/bin/qemu-arm-static"
        mode: '0755'
        remote_src: true

    # 'raspi-copies-and-fills' does not support host architecture, and this generates lots of warnings.
    #   - We move the file until the end to prevent these
    #
    # https://bugs.launchpad.net/qemu/+bug/1813034
    # https://patchwork.kernel.org/patch/10807531/
    # https://www.raspberrypi.org/forums/viewtopic.php?t=235594
    - name: Move preload file to avoid noisy build
      become: true
      shell: "mv {{ raspi_os_mount_point }}/etc/ld.so.preload {{ raspi_os_mount_point }}/etc/ld.so.preload.bak"
      args:
        creates: "{{ raspi_os_mount_point }}/etc/ld.so.preload.bak"
