- hosts: localhost
  become_method: sudo
  gather_facts: false

  vars:
    image_folder: ./
    mount_point: /tmp/pi-top-os

  tasks:

    - name: Don't continue if already mounted...
      stat:
        path: "{{ mount_point }}/recovery"
      register: pt_os_file_details

    - meta: end_play
      when: pt_os_file_details.stat.exists


    - set_fact:
        # TODO: handle this globally
        image_name: new-image

    - set_fact:
        image_path: "{{ image_folder }}{{ image_name }}.img"

    - name: List the loop devices associated with image
      command: "losetup --output=NAME --associated {{image_path}}"
      register: loop_device_check

    - name: Mount all the partitions to loop devices
      command: "partx --add --verbose {{image_path}}"
      become: true
      when: loop_device_check.stdout_lines[1] is not defined

    - name: blkid ptos recovery
      shell: "blkid -l -o export -t LABEL='recovery'"
      register: blkid_pt_os_recovery_stdout

    - debug:
        var: blkid_pt_os_recovery_stdout
        verbosity: 2

    - name: blkid ptos boot
      shell: "blkid -l -o export -t LABEL='boot'"
      register: blkid_pt_os_boot_stdout

    - debug:
        var: blkid_pt_os_boot_stdout
        verbosity: 2

    - name: blkid ptos rootfs
      shell: "blkid -l -o export -t LABEL='rootfs'"
      register: blkid_pt_os_rootfs_stdout

    - debug:
        var: blkid_pt_os_rootfs_stdout
        verbosity: 2

    - set_fact:
        recovery:
          fstype: "{{ blkid_pt_os_recovery_stdout.stdout_lines[-2].replace('TYPE=', '') }}"
          partuuid: "{{ blkid_pt_os_recovery_stdout.stdout_lines[-1].replace('PARTUUID=', '') }}"
        boot:
          fstype: "{{ blkid_pt_os_boot_stdout.stdout_lines[-2].replace('TYPE=', '') }}"
          partuuid: "{{ blkid_pt_os_boot_stdout.stdout_lines[-1].replace('PARTUUID=', '') }}"
        rootfs:
          fstype: "{{ blkid_pt_os_rootfs_stdout.stdout_lines[-2].replace('TYPE=', '') }}"
          partuuid: "{{ blkid_pt_os_rootfs_stdout.stdout_lines[-1].replace('PARTUUID=', '') }}"

    - debug:
        var: recovery
        verbosity: 2

    - debug:
        var: boot
        verbosity: 2

    - debug:
        var: rootfs
        verbosity: 2

    # Always unmount image, this means create mount point works correctly
    # it a quick and easy way to enable re-running without errors
    - name: Unmount image
      shell: "umount --recursive --detach-loop {{ mount_point }}"
      become: true
      args:
        executable: /bin/bash
      # This is lazy way to avoid checking if something is already mounted
      ignore_errors: true

    # When Raspberry Pi OS is mounted to this point it messes up how ansible checks if the directory exists
    # it should be skipped if the directory is mounted
    - name: Create mount point
      file:
        path: "{{mount_point}}"
        state: directory
        recurse: true

    - name: Mount rootfs
      become: true
      mount:
        path: "{{ mount_point }}"
        src: "PARTUUID={{ rootfs.partuuid }}"
        fstype: "{{ rootfs.fstype }}"
        fstab: /tmp/pi-top-fstab
        opts: defaults,noatime
        state: mounted

    - name: Mount boot
      become: true
      mount:
        path: "{{ mount_point }}/boot"
        src: "PARTUUID={{ boot.partuuid }}"
        fstype: "{{ boot.fstype }}"
        fstab: /tmp/pi-top-fstab
        opts: defaults
        state: mounted

    - name: Mount recovery
      become: true
      mount:
        path: "{{ mount_point }}/recovery"
        src: "PARTUUID={{ recovery.partuuid }}"
        fstype: "{{ recovery.fstype }}"
        fstab: /tmp/pi-top-fstab
        opts: defaults
        state: mounted

    - name: Mount proc
      become: true
      command: mount -t proc /proc "{{ mount_point }}/proc"
      args:
        warn: false

    - name: Mount sys
      become: true
      command: mount -t sysfs /sys "{{ mount_point }}/sys"
      args:
        warn: false

    - name: Mount dev
      become: true
      command: mount -o bind /dev "{{ mount_point }}/dev"
      args:
        warn: false

    - name: Mount dev/pts
      become: true
      command: mount -o bind /dev/pts "{{ mount_point }}/dev/pts"
      args:
        warn: false
