- hosts: localhost
  become_method: sudo
  gather_facts: true

  vars:
    raspi_os_mount_point: /tmp/raspi-os
    image_folder: ./
    # TODO: use 'image_name' on localhost if already defined
    image_name: 2022-09-22-raspios-bullseye-armhf
  tasks:
    - name: Unmount Raspberry Pi OS
      shell: "umount --force --verbose {{ raspi_os_mount_point }}{{ item }}"
      loop:
        - /boot/firmware
        - # Not a typo - needed to unmount the root
      ignore_errors: true

    - set_fact:
        image_path: "{{ image_folder }}/{{ image_name }}.img"

    - name: List the loop device(s) associated with image
      command: "losetup --output=NAME --associated {{image_path}}"
      register: loop_device_check

    - name: Delete associated loop device
      shell: "losetup --detach {{ loop_device_check.stdout_lines[1] }}"
      when: loop_device_check.stdout_lines[1] is defined
