name: Build Image, Push to Docker Hub (on master)

on:
  # Run on any commit
  push:
  schedule:
    # Run daily at midnight
    - cron:  '0 0 * * *'

env:
  DOCKER_IMAGE_NAME: "pi-top-os-builder"

jobs:
  build-push-docker-hub:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0

      - name: Login to Docker Hub
        # if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          # push: github.ref == 'refs/heads/master'
          push: true
          tags: pitop/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Show image digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}
