name: pi-topOS Build

on:
  # Run on any commit
  push:
    branches:
      - "**"
  workflow_dispatch:
    # Not required as defaults are handled later on (to support push events)
    inputs:
      REPO_NAME:
        description: 'REPO_NAME'
        required: false
        default: "pi-top-os"
      DISTRO_NAME:
        description: 'DISTRO_NAME'
        required: false
        default: "sirius"
  schedule:
    # Run daily at midnight
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0

      - name: Build
        run: |
          mkdir artifacts

          docker run --tty --privileged \
              -e REPO_NAME="${{ github.event.inputs.REPO_NAME || 'pi-top-os' }}" \
              -e DISTRO_NAME="${{ github.event.inputs.DISTRO_NAME || 'sirius' }}" \
              -e BUILD_NUMBER="${GITHUB_RUN_NUMBER}" \
              -e BUILD_COMMIT="$(git rev-parse HEAD)" \
              -v $(pwd)/artifacts:/artifacts \
              pitop/pi-top-os-builder:latest \
              .

      - name: Get zip filename
        run: echo "ZIP_FILENAME=$(find artifacts -name "*.zip" | head -n1)" >> $GITHUB_ENV

      - name: Get push artifact name
        if: github.event_name == 'push'
        run: echo "ARTIFACT_NAME=pt-os-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      # 'pt-os' artifact name is used by publish.yml
      - name: Get manual trigger artifact name
        if: github.event_name == 'workflow_dispatch'
        run: echo "ARTIFACT_NAME=pt-os" >> $GITHUB_ENV

      - name: Upload OS zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          if-no-files-found: error
          path: ${{ env.ZIP_FILENAME }}

      - name: Upload metadata
        uses: actions/upload-artifact@v2
        with:
          name: metadata
          if-no-files-found: error
          path: |
            output-files/*
